services:
  - type: web
    name: cthreebackend
    env: python
    buildCommand: "./build.sh"
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: cthreedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: cthreebackend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://cthree.vercel.app
      - key: DJANGO_SETTINGS_MODULE  # Add this
        value: myproject.settings
      - key: PORT  # Add this
        value: 8000

databases:
  - name: cthreedb
    plan: free
    region: singapore