services:
  - type: web
    name: cthreebackend
    env: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: cthreedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: cthreebackend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://cthree.vercel.app

databases:
  - name: cthreedb
    databaseName: cthreedb
    user: cthreeuser
    plan: free
    region: singapore