services:
  - type: web
    name: cthreebackend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: business-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: your-app-name.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-app-name.vercel.app

databases:
  - name: cthreedb
    plan: free