services:
  - type: web
    name: cthreebackend
    env: python
    buildCommand: "./build.sh"  # Changed from pip install
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cthreedb  # Changed from business-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: cthreebackend.onrender.com  # Your actual Render URL
      - key: CORS_ALLOWED_ORIGINS
        value: https://cthree.vercel.app  # Your actual frontend URL

databases:
  - name: cthreedb
    plan: free
    region: singapore